### PR TITLE
Initial Research merge

### PR DESCRIPTION
**Pull request by kj5699**

### CODE REVIEW

**Review by sejall — COMMENTED** [review]
ok

**Review by meenaljain8001 — COMMENTED** [review]
Have we included all the features that we have discussed yesterday?

**Review by meenaljain8001 — APPROVED** [review]

**Comment by kj5699** [comment]
> Have we included all the features that we have discussed yesterday?

That is exactly what you need to review.

**Comment by joshinakul** [comment]
plenty of features for now!

**Pull request merged**
